name: Token

on:
  workflow_dispatch:
  
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - uses: matthewtamayo/sample-action@main
      - name: show repo
        shell: bash
        run: echo "good"
